# Generated by Django 4.2.3 on 2023-07-30 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('dniEstudiante', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidoPaterno', models.CharField(max_length=35, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(max_length=35, verbose_name='Apellido Materno')),
                ('fechaNacimiento', models.DateField()),
                ('numeroCelular', models.IntegerField(verbose_name='Número de Celular')),
                ('correoEle', models.CharField(max_length=35, verbose_name='Correo Electrónico')),
                ('departamento', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IDnivel', models.CharField(max_length=30, verbose_name='ID del Nivel')),
                ('modalidad', models.CharField(max_length=35, verbose_name='Modalidad')),
                ('nivel', models.CharField(max_length=35, verbose_name='Nivel')),
                ('frecuencia', models.CharField(max_length=35, verbose_name='Frecuencia')),
                ('horario', models.CharField(max_length=35, verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('dniProfesor', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidoPaterno', models.CharField(max_length=35, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(max_length=35, verbose_name='Apellido Materno')),
                ('idioma', models.CharField(max_length=35, verbose_name='Idioma a enseñar')),
                ('fechaNacimiento', models.DateField()),
                ('numeroCelular', models.IntegerField(verbose_name='Número de Celular')),
                ('correoEle', models.CharField(max_length=35, verbose_name='Correo Electrónico')),
                ('sueldo', models.IntegerField(verbose_name='Sueldo Mensual')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='PagoNivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechapago', models.DateField()),
                ('Mesnivel', models.CharField(max_length=15, verbose_name='Mes de nivel')),
                ('Añonivel', models.CharField(max_length=15, verbose_name='Año de nivel')),
                ('precio', models.CharField(max_length=15, verbose_name='Precio')),
                ('metodopago', models.CharField(max_length=15, verbose_name='Metodo de pago')),
                ('DNIestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.estudiante', verbose_name='DNI Estudiante')),
                ('DNIprofesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.profesores', verbose_name='DNI Profesor')),
                ('Idnivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.niveles', verbose_name='ID del Nivel')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
