# Generated by Django 4.2.3 on 2023-07-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveles',
            name='nivel',
            field=models.CharField(choices=[('B1', 'Básico 1'), ('B2', 'Básico 2'), ('B3', 'Básico 3'), ('I1', 'Intermedio 1'), ('I2', 'Intermedio 2'), ('A', 'Avanzado')], default='B1', max_length=2),
        ),
    ]
